# Маппинг перенаправлений запросов на серверы с соответствующих им устройств,
# ключами являются хост и порт сервера, а значениями диапазон номеров устройств.
#    - "8080": "0-2"     <-  Staging
#    - "8090": "3-10"    <-  Production-like
#    - "9000": "11-150"  <-  Production
[[PROXY_MAP]]
host = "servers"
port = 8080
devices = "0-2"

[[PROXY_MAP]]
host = "servers"
port = 8090
devices = "3-10"

[[PROXY_MAP]]
host = "servers"
port = 9000
devices = "11-150"


[COMMON]
SERVERS_HOST = "servers"

# Сервер по-умолчанию, куда будут направлены запросы,
# когда не найден адрес в маппинге перенаправлений
DEFAULT_SERVER = "servers:8010"

# Задержка ответа на запрос(в секундах)
DELAY_TIME = 2

