# Маппинг серверов и соответствующих им устройств
MAP: {
  127.0.0.1: {
    8888: [terminal_0],
    9999: [terminal_1],
  }
}


# Сервер и порт по-умолчанию, куда будут направлены запросы,
# когда не найден адрес в маппинге.
DEFAULT_SERVER: {
  HOST: 127.0.0.1,
  PORT: 8080
}


# Задержка ответа на запрос(в секундах)
DELAY_TIME: 2