# Маппинг перенаправлений запросов на серверы с соответствующих им устройств,
# ключами являются хост и порт сервера, а значениями диапазон номеров устройств.
MAP: {
  127.0.0.1: {
    8080: 0-2,     # Staging
    8090: 3-10,    # Production-like
    9000: 11-150,  # Production
  }
}

# Сервер по-умолчанию, куда будут направлены запросы,
# когда не найден адрес в маппинге перенаправлений.
DEFAULT_SERVER: "127.0.0.1:8010"


# Задержка ответа на запрос(в секундах)
DELAY_TIME: 2