# Маппинг серверов и соответствующих им устройств
MAP: {
  1-10 : "127.0.0.1:8888",
  11-20 : "127.0.0.1:9999"
}

# Сервер по-умолчанию, куда будут направлены запросы,
# когда не найден адрес в маппинге.
DEFAULT_SERVER: "127.0.0.1:8080"


# Задержка ответа на запрос(в секундах)
DELAY_TIME: 2